#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - py3-pip
  - curl
users:
  - name: cloud
    passwd: $6$rounds=4096$vln/.aPHBOI7BMYR$bBMkqQvuGs5Gyd/1H5DP4m9HjQSy.kgrxpaGEHwkX7KEFV8BS.HZWPitAtZ2Vd8ZqIZRqmlykRCagTgPejt1i.
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    chpasswd: {expire: False}
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDJPiE9aJL1IFP8fOZdBKW3HxGnhcRzKKw2jznutjZxyCPOepreu+UEDnKXa3bd+asylx6prib4J7rThm/+AKB8vCLIjP6l4tgr12V7rommXWO3NtES4fi3SbR8g+1V2ARDQ+SgMtXoFFMBmI9J2DZKX/kyo5MszgdeT3HLOeTsPw== demo
runcmd:
  - python3 -m venv /opt/venv
  - /opt/venv/bin/pip install flask flask-cors psycopg2-binary gunicorn python-dotenv
  - mkdir /app
  - curl https://raw.githubusercontent.com/fl64/dvp-demo-app/master/apps/backend/app.py > /app/app.py
  - rc-update add flask-app default
  - rc-service flask-app start
write_files:
  - path: /etc/init.d/flask-app
    permissions: "0755"
    content: |
      #!/sbin/openrc-run

      description="Flask App Service with Gunicorn"
      command="/opt/venv/bin/gunicorn"
      command_args="--workers 4 --bind 0.0.0.0:5000 app:app --daemon"
      pidfile="/var/run/flask-app.pid"
      directory="/app"
      depend() {
          need net
      }

      start_pre() {
          rm -f /var/run/flask-app.pid
      }
  - path: /app/.env
    permissions: "0644"
    content: |
      export DB_HOST=db.demo-db.svc.cluster.local
      export DB_USER=myuser
      export DB_PASSWORD=mypassword
      export DB_NAME=mydb
final_message: "\U0001F525\U0001F525\U0001F525 The system is finally up, after $UPTIME seconds \U0001F525\U0001F525\U0001F525"
